version: "3.9"

services:
  frontend:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: dev
      POSTGRES_PASSWORD: root
    ports:
      - 5342:5342
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
